name: Run all tests

on: [push, pull_request]

env:
  PIP: "env PIP_DISABLE_PIP_VERSION_CHECK=1
            PYTHONWARNINGS=ignore:DEPRECATION
            pip --no-cache-dir"

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12, 3.13, 3.14, "pypy-3.11"]

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Show Python version
      run: python -V

    - name: Install the package
      run: $PIP install .

    - name: Run the tests
      run: python -m unittest discover py65.tests

    - name: Run the end-to-end tests
      run: |
        $PIP install pexpect
        END_TO_END=1 python -m unittest discover py65.tests
